### PR TITLE
Add prayers layout

### PR DESCRIPTION
**Pull request by fayez-nazzal**
## Add prayers layout

- New layout "Group by prayers", and it's the new default
- Add changed_on to masjids tables; color coding to be done in another PR
- No changes in Jumaas yet, it's only on the masjids layout (which was the default before this PR)

### CODE REVIEW

**Comment by fayez-nazzal** [comment]
@hammady Can you try to run this and give your opinion?

**Review by hammady — CHANGES_REQUESTED** [review]
Looks awesome. I have some minor comments:
1. I tried generating it locally but got the below error:
```
file:///private/tmp/generator/svelte/.svelte-kit/output/server/chunks/MasjidLastUpdated.js:8                                                           
import { keys } from "lodash";                                                                                                                         
         ^^^^                                                                                                                                          
SyntaxError: Named export 'keys' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named expor
ts.                                                                                                                                                    
CommonJS modules can always be imported via the default export, for example using:                                                                     
                                                                                                                                                       
import pkg from 'lodash';                                                                                                                              
const { keys } = pkg;                                                                                                                                  
```
By replacing line 5 in utils.js with the recommended change it worked. I think it will break on CI without this change.

2. When clicking a masjid name in the "group by prayer", it jumps to the other layout but because the page header covers a fixed part of the screen, the masjid name and address are hidden behind the header. Let's not try fixing it and I suggest removing this header for now. The max is 20 masjids anyway and with the new layout, they all appear without scroll with the ability to click for details. 
3. The last updated column has a dot after the relative time which looks odd. Can we remove?
4. Changed on is missing from the old layout. Please add it as a third column.

**Comment by fayez-nazzal** [comment]
> Looks awesome. I have some minor comments:
> 
> 1. I tried generating it locally but got the below error:
> 
> ```
> file:///private/tmp/generator/svelte/.svelte-kit/output/server/chunks/MasjidLastUpdated.js:8                                                           
> import { keys } from "lodash";                                                                                                                         
>          ^^^^                                                                                                                                          
> SyntaxError: Named export 'keys' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named expor
> ts.                                                                                                                                                    
> CommonJS modules can always be imported via the default export, for example using:                                                                     
>                                                                                                                                                        
> import pkg from 'lodash';                                                                                                                              
> const { keys } = pkg;                                                                                                                                  
> ```
> 
> By replacing line 5 in utils.js with the recommended change it worked. I think it will break on CI without this change.
> 
> 2. When clicking a masjid name in the "group by prayer", it jumps to the other layout but because the page header covers a fixed part of the screen, the masjid name and address are hidden behind the header. Let's not try fixing it and I suggest removing this header for now. The max is 20 masjids anyway and with the new layout, they all appear without scroll with the ability to click for details.
> 3. The last updated column has a dot after the relative time which looks odd. Can we remove?
> 4. Changed on is missing from the old layout. Please add it as a third column.

Yep, I will make the change. Regarding the import issue, this type of lodash import works in the client but not in the server. It should be `import keys from 'lodash/keys'`, but auto import sometimes imports the wrong ones.

This change is better than suggestion because we only import what we want, nothing else.

**Comment by fayez-nazzal** [comment]
@hammady Sorry for the delay, I added a PR description, and here are screenshots.

There are room for a lot of improvement, but I feel that this PR took too much changes more than necessary, will follow up with more PRs next morning.

image

image

**Review by hammady — APPROVED** [review]
LGTM!

**Pull request merged**
